---
#Setting up Hadoop
- name: Create service account for Hadoop
  user: name={{ hadoop_user }}
        system=yes
        state=present
        groups="{{ hadoop_user_groups | join(',') }}"
  tags: ["hadoop-user"]

- name: Ensure Hadoop directory exists
  file: path="{{ hadoop_dir }}" state=directory owner={{ hadoop_user }} group={{ hadoop_user_groups[0] }} mode=g+rw

- name: Ensure Hadoop configuration directory exists
  file: path="{{ hadoop_parent_conf_dir }}" state=directory
  tags: ["config"]

- name: Ensure Hadoop log and run directories exist
  file: path="{{ item }}"
        owner={{ hadoop_user }}
        group={{ hadoop_user_groups[0] }}
        mode=0755
        state=directory
  with_items:
    - "{{ hadoop_log_dir }}"
    - "{{ hadoop_run_dir }}"

- name: Download Hadoop distribution
  get_url: url="{{ hadoop_mirror }}/hadoop-{{ hadoop_version }}//hadoop-{{ hadoop_version }}.tar.gz"
           dest="{{ hadoop_src_dir }}/hadoop-{{ hadoop_version }}.tar.gz"

- name: Extract Hadoop distribution
  unarchive: src="{{ hadoop_src_dir }}/hadoop-{{ hadoop_version }}.tar.gz"
             dest="{{ hadoop_usr_parent_dir }}"
             copy=no
             creates="{{ hadoop_usr_parent_dir }}/hadoop-{{ hadoop_version }}"

- name: Setup Hadoop distribution symlinks
  file: src="{{ item.src }}"
        dest="{{ item.dest }}"
        state=link
  with_items:
    - { src: "{{ hadoop_usr_parent_dir }}/hadoop-{{ hadoop_version }}", dest: "{{ hadoop_usr_dir }}" }
    - { src: "{{ hadoop_usr_parent_dir }}/hadoop-{{ hadoop_version }}/etc/hadoop", dest: "{{ hadoop_conf_dir }}" }
  tags: ["symlinks"]

- name: Create shims for Hadoop binaries
  template: src=hadoop-shim.j2
            dest="/usr/bin/{{ item }}"
            mode=0755
  with_items:
    - hadoop
    - hdfs
    - yarn
  tags: ["shims"]

- name: Configure hadoop core-site
  template: src=core-site.xml.j2
            dest="{{ hadoop_conf_dir }}/core-site.xml"
  tags: ["core-site"]

- name: Configure hadoop hdfs-site
  template: src=hdfs-site.xml.j2
            dest="{{ hadoop_conf_dir }}/hdfs-site.xml"
  tags: ["config"]

- name: Hadoop config slaves
  template:
    src: slaves.j2
    dest: '{{ hadoop_conf_dir }}/slaves'

- name: Hadoop config masters
  template:
    src: masters.j2
    dest: '{{ hadoop_conf_dir }}/masters'

- name: Copy hadoop-hdfs.systemd
  template: src=hadoop-hdfs.systemd.j2 dest=/etc/systemd/system/hadoop-hdfs.service
