---
- name: Configure hadoop env
  template: src=../templates/hadoop-env.sh.j2
            dest="{{ hadoop_conf_dir }}/hadoop-env.sh"

- name: Configure hadoop core-site
  template: src=../templates/core-site.xml.j2
            dest="{{ hadoop_conf_dir }}/core-site.xml"

- name: Configure hadoop hdfs-site
  template: src=../templates/hdfs-site.xml.j2
            dest="{{ hadoop_conf_dir }}/hdfs-site.xml"

- name: Hadoop config slaves
  template:
    src: ../templates/slaves.j2
    dest: '{{ hadoop_conf_dir }}/slaves'

- name: Hadoop config masters
  template:
    src: ../templates/masters.j2
    dest: '{{ hadoop_conf_dir }}/masters'

- name: Start namenode
  shell: "{{ hadoop_usr_dir }}/bin/hdfs --daemon start namenode"
  register: hadoop_namenode
  when: inventory_hostname in groups['hadoop-namenode']

- name: Start datanodes
  shell: "{{ hadoop_usr_dir }}/bin/hdfs --daemon start datanode"
  register: hadoop_datanodes
  when: inventory_hostname in groups['hadoop-datanode']

- name: Start HDFS
  systemd: name=hadoop-hdfs state=started daemon_reload=yes
  when: inventory_hostname in groups['hadoop-namenode']
