---

- hosts: all
  remote_user: root
  roles:
    - common
  any_errors_fatal: true

- hosts: spark
  remote_user: root
  vars_files:
   - vars/common_vars.yml
   - vars/spark_vars.yml
   - vars/minio_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
    HADOOP_LOG_DIR: "{{ hadoop_log_dir }}"
    HADOOP_CONF_DIR: "{{ hadoop_conf_dir }}"
  roles:
    - spark
  any_errors_fatal: true

- hosts: spark-master
  remote_user: root
  vars_files:
   - vars/spark_vars.yml
   - vars/minio_vars.yml
   - vars/common_vars.yml
  roles:
    - spark-master

- hosts: spark
  remote_user: root
  vars_files:
   - vars/spark_vars.yml
   - vars/minio_vars.yml
   - vars/common_vars.yml
  roles:
    - spark-slave
