---
- hosts: spark
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/spark_vars.yml
   - vars/minio_vars.yml
  tasks:
    - include: roles/jupyterhub/tasks/stop-jupyterhub.yml
    - include: roles/spark/tasks/stop-spark.yml

- hosts: minio
  remote_user: ubuntu
  become: true
  tasks:
    - include: roles/minio/tasks/stop-minio.yml

- hosts: hadoop
  remote_user: ubuntu
  become: true
  vars_files: 
  - vars/common_vars.yml
  - vars/hadoop_vars.yml
  environment: 
    JAVA_HOME: "{{ java_home }}"
  tasks:
    - include: roles/hadoop/tasks/stop-hadoop.yml

