---
- hosts: hadoop
  remote_user: root
  vars_files: 
  - vars/common_vars.yml
  - vars/hadoop_vars.yml
  environment: 
    JAVA_HOME: "{{ java_home }}"

  tasks:
    - include: roles/hadoop/tasks/start-hadoop.yml

- hosts: minio
  remote_user: root

  tasks:
    - include: roles/minio/tasks/start-minio.yml

- hosts: spark
  remote_user: root
  vars_files:
   - vars/spark_vars.yml
   - vars/minio_vars.yml

  tasks:
    - include: roles/spark/tasks/start-spark.yml
    - include: roles/jupyterhub/tasks/start-jupyterhub.yml
