---
- hosts: hadoop
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files: 
   - vars/common_vars.yml
   - vars/minio_vars.yml
   - vars/hadoop_vars.yml
  environment: 
    JAVA_HOME: "{{ java_home }}"
    HADOOP_LOG_DIR: "{{ hadoop_log_dir }}"
    HADOOP_CONF_DIR: "{{ hadoop_conf_dir }}"
  tasks:
    - include: roles/hadoop/tasks/start-hadoop.yml
  tags:
    - hadoop

- hosts: minio
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/minio_vars.yml
  tasks:
    - include: roles/minio/tasks/start-minio.yml
  tags:
    - minio

- hosts: spark
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/minio_vars.yml
   - vars/hadoop_vars.yml
   - vars/spark_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
    HADOOP_LOG_DIR: "{{ hadoop_log_dir }}"
    HADOOP_CONF_DIR: "{{ hadoop_conf_dir }}"
  tasks:
    - include: roles/spark/tasks/start-spark.yml
  tags:
    - spark

- hosts: cassandra
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/spark_vars.yml
   - vars/cassandra_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
  tasks:
    - include: roles/cassandra/tasks/start-cassandra.yml
  tags:
    - cassandra

- hosts: dask
  gather_facts: yes
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/dask_vars.yml
  tasks:
    - include: roles/dask/tasks/start-dask.yml
  tags:
    - dask

- hosts: jupyterhub
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/spark_vars.yml
   - vars/jupyterhub_vars.yml
  tasks:
    - include: roles/jupyterhub/tasks/start-jupyterhub.yml
  tags:
    - jupyterhub
