---
- name: Ensure Jupyter source directory exists
  file: path="{{ jupyterhub_src_dir }}" state=directory group=users mode=g+rw

- name: Add an Apt signing key for the latest nodejs
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Deps 4 JupyterHub notebook
  apt: name={{ item }}
  with_items:
    - npm
    - nodejs
    - libffi-dev
    - libcurl4-gnutls-dev
    - zlib1g-dev


- name: configurable-http-proxy
  npm: name=configurable-http-proxy global=yes

- name: Jupyter for Python 3
  pip: name=jupyter executable=pip3

- name: ipykernel for Python 3
  pip: name=ipykernel executable=pip3

- name: Copy irkernel_install
  template: src=irkernel_install.r.j2
            dest="{{ jupyterhub_src_dir }}/irkernel_install.r"

- name: Install Rscript
  apt: name=r-base-core

#- name: Install irkernel
#  shell: "Rscript {{ jupyterhub_src_dir }}/irkernel_install.r"

- name: Python 3 to Jupyter
  shell: /usr/bin/python3 -m ipykernel install

- name: Toree (Spark Jupyter)
  include: toree.yml

- name: JupyterHub
  pip: name=jupyterhub executable=pip3

- name: /etc/jupyterhub
  file: path=/etc/jupyterhub state=directory

- name: JupyterHub config
  command: jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py creates=/etc/jupyterhub/jupyterhub_config.py

# Default hub_port in use by Spark
- name: Bind JupyterHub to all interfaces, port 8011, and define JAVA_HOME
  blockinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    block: |
      c.JupyterHub.ip = '0.0.0.0'
      c.Spawner.environment = {'JAVA_HOME':'{{ java_home }}'}
      c.JupyterHub.hub_port = 8011
      c.NotebookApp.iopub_data_rate_limit = 100000000

- name: Start/stop script JupyterHub
  copy: src=jupyterhub.systemd dest=/etc/systemd/system/jupyterhub.service

- name: Install modules needed for Applications using Spark Jupyter
  include: modules.yml
  tags:
    - jupyterhub_modules
