---

#Inpired in 
#https://ibm-watson-data-lab.github.io/pixiedust/install.html

- name: Ensure Pixiedust home directory exists
  file: path="{{ pixiedust_home_dir }}" state=directory owner=ubuntu group=users mode=g+rw

- name: Ensure Pixiedust bin directory exists
  file: path="{{ pixiedust_home_dir }}/bin" state=directory group=users mode=g+rw

- name: Install dependencies for ansible
  pip: name={{ item }} executable=pip
  with_items:
    - pexpect

- name: Install dependencies for pixiedust
  pip: name={{ item }} executable=pip3
  with_items:
    - traitlets
    - pyyaml
    - requests

- name: Install pixiedust
  pip: name=pixiedust executable=pip3

- name: Pixiedust for Jupyter
  expect:
    command: "jupyter pixiedust install"
    responses:
      'Keep y/n [y]?': "n" 
      'Please enter a PIXIEDUST_HOME location': "{{ pixiedust_home_dir }}"
      'Step 2: Please enter a SPARK_HOME location': "{{ spark_usr_dir }}"
      'Please enter a SCALA_HOME location': "/usr/share/scala/"
      'Please enter a Kernel Name': "Python with Pixiedust (Spark 2.1)"

- name: Use python3.5
  lineinfile:
    dest: /root/.local/share/jupyter/kernels/pythonwithpixiedustspark21/kernel.json
    regexp: '^\s\s*\"python\",'
    line: '  "python3.5",'

- name: Copy kernel to global kernels dir
  shell: "cp -r /root/.local/share/jupyter/kernels/pythonwithpixiedustspark21/ /usr/local/share/jupyter/kernels/"
