---
# Applied fix at http://stackoverflow.com/questions/40831991/jupyter-apache-toree-scala-kernel-is-busy
#
# Important to mention the information about which toree to use came from:
# https://medium.com/@faizanahemad/machine-learning-with-jupyter-using-scala-spark-and-python-the-setup-62d05b0c7f56

- name: Toree (Spark Jupyter) installation
  pip: executable=pip3 name={{ toree_pip_name_url }}

- name: Toree to Jupyter
  shell: jupyter toree install --python_exec='python3.5' --spark_home='{{ spark_usr_dir }}' --spark_opts='--master=spark://{{ groups['spark-master'][0] }}:7077' --interpreters=Scala,PySpark,SparkR,SQL creates=/usr/local/share/jupyter/kernels/apache_toree_scala
