---

- name: Ensure Cassandra directory exists
  file:
    path: "{{ cassandra_dir }}"
    state: directory
    group: users
    mode: g+rw

- name: Create Cassandra data file directories
  file:
    path: "{{ cassandra_dir }}/data/"
    state: directory
    group: users
    mode: g+rw

- name: Create Cassandra saved caches directories
  file:
    path: "{{ cassandra_dir }}/saved_caches/"
    state: directory
    group: users
    mode: g+rw

- name: Create Cassandra commitlog directory
  file:
    path: "{{ cassandra_dir }}/commitlog/"
    state: directory
    group: users
    mode: g+rw

# Instructions were obtained from here
#http://cassandra.apache.org/download/

- name: Add Apache repository of Cassandra
  apt_repository:
    repo: 'deb {{ cassandra_repo_url }} {{ cassandra_version }} main'

- name: Add Apache Cassandra repository keys
  apt_key: 
    id: "{{ cassandra_repo_key }}"
    state: present
    keyserver: "{{ cassandra_repo_key_server }}"

- name: Update apt cache
  apt: update_cache=yes

- name: Install Cassandra
  apt: name=cassandra

#Configure Cassandra
- name: Configure Cassandra
  template: src=cassandra.yaml.j2
            dest="{{ cassandra_conf_dir }}/cassandra.yaml"
  tags: ["config"]

