---
- name: Create service account for Cassandra
  user: name={{ cassandra_user }}
        system=yes
        state=present
        groups="{{ cassandra_user_groups | join(',') }}"
  tags: ["cassandra-user"]

- name: Directory for cassandra modules
  file:
    path: "{{ emma_modules_dir }}/cassandra"
    state: directory
    group: users
    mode: g+rw

- name: Ensure Cassandra directory exists
  file:
    path: "{{ cassandra_dir }}"
    state: directory
    owner: cassandra
    group: users
    mode: g+rw

- name: Create Cassandra data file directories
  file:
    path: "{{ cassandra_dir }}/data/"
    state: directory
    owner: cassandra
    group: users
    mode: g+rw

- name: Create Cassandra saved caches directories
  file:
    path: "{{ cassandra_dir }}/saved_caches/"
    state: directory
    owner: cassandra
    group: users
    mode: g+rw

- name: Create Cassandra commitlog directory
  file:
    path: "{{ cassandra_dir }}/commitlog/"
    state: directory
    owner: cassandra
    group: users
    mode: g+rw

- name: Create Cassandra cdc_raw directory
  file:
    path: "{{ cassandra_dir }}/cdc_raw/"
    state: directory
    owner: cassandra
    group: users
    mode: g+rw


# Instructions were obtained from here
#http://cassandra.apache.org/download/

- name: Add Apache repository of Cassandra
  apt_repository:
    repo: 'deb {{ cassandra_repo_url }} {{ cassandra_version }} main'

- name: Add Apache Cassandra repository keys
  apt_key: 
    id: "{{ cassandra_repo_key }}"
    state: present
    keyserver: "{{ cassandra_repo_key_server }}"

- name: Update apt cache
  apt: update_cache=yes

- name: Install Cassandra
  apt: name=cassandra

#Configure Cassandra
- name: Template seed list
  template: src=seeds.j2 dest=/tmp/seed_list mode=0664

- name: Load seed list
  shell: cat /tmp/seed_list
  register: seed_list

- name: Set seeds fact
  set_fact: seeds={{ seed_list.stdout }}

- debug: var=seeds

- name: Configure Cassandra
  template: src=cassandra.yaml.j2
            dest="{{ cassandra_conf_dir }}/cassandra.yaml"

#Install Cassandra Lucene index plugin
- name: Directory for cassandra modules
  file:
    path: "{{ emma_modules_dir }}/cassandra/cassandra_lucene"
    state: directory
    group: users
    mode: g+rw

- name: Get Cassandra Lucene index jars and dependencies
  get_url:
    url: "http://central.maven.org/maven2/{{ item.group }}/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.jar"
    dest: "{{ emma_modules_dir }}/cassandra/cassandra_lucene/{{ item.name }}-{{ item.version }}.jar"
  with_items:
    - { group: 'com/stratio/cassandra', name: 'cassandra-lucene-index-plugin', version: '3.11.1.0' }
    - { group: 'com/github/rholder', name: 'snowball-stemmer', version: '1.3.0.581.1' }
    - { group: 'com/google/code/findbugs', name: 'jsr305', version: '3.0.1' }
    - { group: 'org/apache/lucene', name: 'lucene-core', version: '5.5.4' }
    - { group: 'org/apache/lucene', name: 'lucene-analyzers-common', version: '5.5.4' }
    - { group: 'org/apache/lucene', name: 'lucene-spatial', version: '5.5.4' }
    - { group: 'org/apache/lucene', name: 'lucene-queryparser', version: '5.5.4' }
    - { group: 'com/vividsolutions', name: 'jts-core', version: '1.14.0' }

