---
- name: Include global vars
  include_vars:
    file: '../../../vars/cassandra_vars.yml'

#Configure Cassandra
- name: Configure Cassandra
  template: src=../templates/cassandra.yaml.j2
            dest="{{ cassandra_conf_dir }}/cassandra.yaml"

- name: Cassandra env
  copy: src=../files/cassandra-env.sh dest=/etc/cassandra/cassandra-env.sh

#Start Cassandra
- name: Cassandra seeds started
  systemd: name=cassandra state=started daemon_reload=yes
  when: inventory_hostname in groups['cassandra-seeds']

- name: Cassandra all other nodes started
  systemd: name=cassandra state=started daemon_reload=yes
  when: inventory_hostname in groups['cassandra-nodes']
