galaxy_info:
  author: Romulo Goncalves
  description: Install and configure the Minio S3 compatible object storage server on Debian/Ubuntu
  min_ansible_version: 0.1
  license: Apache 2.0
  issue_tracker_url: https://github.com/nlesc-sherlock/emma/issues

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - vivid
        - wily
        - xenial

dependencies: []
