- hosts: spark-master
  remote_user: root
  vars_files:
   - ../../vars/spark_vars.yml
   - ../../vars/minio_vars.yml
   - ../../vars/common_vars.yml

  tasks:
  - name: JupyterHub started
    systemd: name=jupyterhub state=started daemon_reload=yes
