---
- name: Spark config slaves
  template:
    src: slaves.j2
    dest: '{{ spark_conf_dir }}/conf/slaves'
- name: Copy start-master.systemd
  template: src=spark-master.systemd.j2 dest=/etc/systemd/system/spark-master.service
- name: Spark-master started
  systemd: name=spark-master state=started daemon_reload=yes
- include: jupyter.yml
