---
- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true
  roles:
    - glusterfs
  any_errors_fatal: true

- hosts: glusterfs-primary
  gather_facts: no
  remote_user: ubuntu
  become: true
  tasks:
  - include: ../roles/glusterfs/tasks/create-volume.yml

- hosts: glusterfs
  gather_facts: no
  remote_user: ubuntu
  become: true
  tasks:
  - include: ../roles/glusterfs/tasks/mount-volume.yml
  - include: ../roles/glusterfs/tasks/docker-glusterfs.yml