---
#Inspired in the following how-to
#https://www.1and1.com/cloud-community/learn/containers/docker/using-gluster-for-a-distributed-docker-storage-volume/
#Instead of installing from source we used the binaries from:
#https://github.com/watson81/docker-volume-glusterfs/
- name: download and untar docker-volume-glusterfs
  unarchive:
    src: https://github.com/watson81/docker-volume-glusterfs/releases/download/v0.1.1-alpha/docker-volume-glusterfs-0.1.1-alpha-linux_386.tar.gz
    dest: /usr/bin
    remote_src: True
    group: root
    owner: root
- name: add systemd file for docker-glusterfs
  template:
    src: ../templates/docker-glusterfs.systemd.j2
    dest: /etc/systemd/system/docker-glusterfs.service
- name: enable docker-glusterfs service    
  systemd:
    state: started
    daemon_reload: yes
    name: docker-glusterfs
    enabled: yes
