---
- name: Spark-shuffle stopped
  systemd: name=spark-shuffle state=stopped daemon_reload=yes
  when: inventory_hostname in groups['spark-worker']

- name: Spark-slave stopped
  systemd: name=spark-slave state=stopped daemon_reload=yes
  when: inventory_hostname in groups['spark-worker']

- name: Spark-master stopped
  systemd: name=spark-master state=stopped daemon_reload=yes
  when: inventory_hostname in groups['spark-master']

