---
- name: Include defaults
  include_vars:
    file: '../../../vars/spark_vars.yml'

- name: Configure Spark environment
  template: src=../templates/spark-env.sh.j2
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}-bin-without-hadoop/conf/spark-env.sh"
  tags: ["config"]

- name: Configure Spark defaults config file
  template: src=../templates/spark-defaults.conf.j2
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}-bin-without-hadoop/conf/spark-defaults.conf"
  tags: ["config"]

- name: Configure Hive defaults site file
  template: src=../templates/hive-site.xml.j2
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}-bin-without-hadoop/conf/hive-site.xml"
  tags: ["config"]

- name: Spark-master started
  systemd: name=spark-master state=started daemon_reload=yes
  when: inventory_hostname in groups['spark-master']

- name: Spark-slave started
  systemd: name=spark-slave state=started daemon_reload=yes
  when: inventory_hostname in groups['spark-worker']

- name: Spark-shuffle started
  systemd: name=spark-shuffle state=started daemon_reload=yes
