---
- name: Configure Spark environment
  template: src=spark-env.sh.j2
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}/conf/spark-env.sh"
  tags: ["config"]

- name: Configure Spark defaults config file
  template: src=spark-defaults.conf.j2
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}/conf/spark-defaults.conf"
  tags: ["config"]

- name: Configure Hive defaults site file
  template: src=hive-site.xml.j2
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}/conf/hive-site.xml"
  tags: ["config"]

- name: Spark-master started
  systemd: name=spark-master state=started daemon_reload=yes
  when: inventory_hostname in groups['spark-master']

- name: Spark-slave started
  systemd: name=spark-slave state=started daemon_reload=yes
  when: inventory_hostname in groups['spark-worker']

- name: Spark-shuffle started
  systemd: name=spark-shuffle state=started daemon_reload=yes
  when: inventory_hostname in groups['spark-worker'] and inventory_hostname not in groups['spark-master']
