---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: create minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    shell: /bin/bash

- include: server.yml
  when: not skip_server

- include: client.yml
  when: not skip_client

- name: Install S3 client
  apt: name=s3cmd

- name: Configure s3cmd config file
  template: src=s3cfg.j2
            dest="/home/ubuntu/.s3cfg"
  tags: ["s3cmd_config"]
