---
- name: Include defaults
  include_vars:
    file: '../../../vars/minio_vars.yml'

- name: Configure s3cmd config file
  template: src=../templates/s3cfg.j2
            dest="/home/ubuntu/.s3cfg"
  tags: ["s3cmd_config"]

- name: start the minio service
  systemd:
    name: minio
    state: started
    daemon_reload: yes
