---
# Download jars for GeoTrellis
- name: Copy build.gradle
  copy: src=build.gradle dest=/home/ubuntu/build.gradle

- name: Gradle install dependencies
  shell: gradle downloadDependencies

#Geotrellis for Python
- name: add repository for GDAL Python bindings
  apt_repository: repo=ppa:ubuntugis/ubuntugis-unstable

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade APT to the lastest packages
  apt: upgrade=full

- name: Install GDAL Python bindings
  apt: name={{ item }}
  with_items:
    - python-gdal
    - python3-gdal

