---
# Download jars for GeoTrellis
- name: Ensure GeoTrellis dir exists
  file: path="{{ emma_modules_dir }}/geotrellis" state=directory group=users mode=g+rw

- name: Copy build.gradle
  template: src=build.gradle.j2 dest={{ emma_modules_dir }}/geotrellis/build.gradle

- name: Gradle install dependencies
  shell: gradle -b {{ emma_modules_dir }}/geotrellis/build.gradle downloadDependencies

#Geotrellis for Python
- name: add repository for GDAL Python bindings
  apt_repository: repo=ppa:ubuntugis/ubuntugis-unstable

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade APT to the lastest packages
  apt: upgrade=full

- name: Install GDAL Python bindings
  apt: name={{ item }}
  with_items:
    - python-gdal
    - python3-gdal

