---
- name: Copy start-slave.systemd
  template: src=spark-slave.systemd.j2 dest=/etc/systemd/system/spark-slave.service
- name: Copy start-shuffle.systemd
  template: src=spark-shuffle.systemd.j2 dest=/etc/systemd/system/spark-shuffle.service
