---
- name: Start manager
  command: docker swarm init --force-new-cluster --advertise-addr {{ docker_manager_ip }}
  register: swarm_init_out

- name: retrieve swarm manager token
  shell: docker swarm join-token -q manager
  register: swarm_manager_token
