users:
  - name: emma
    uid: 1100
    # Password created with `mkpasswd --method=SHA-512 pass1234`
    password: $6$6/6NkDn01w$6ld/sdc/B42cVtSNFQTQLlNPYOqin8m4kluy.QbvtLraHLliTs5QaPIYJcKyYr7KKhsY2znFZLSC2YzdROKwZ.
    # Also add roles/common/files/<username>.key and roles/common/files/<username>.key.pub
    # with ssh-keygen -f roles/common/files/<username>.key
