---
- hosts: hadoop
  remote_user: root
  vars_files:
   - ../vars/common_vars.yml
   - ../vars/hadoop_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
    HADOOP_LOG_DIR: "{{ hadoop_log_dir }}"
    HADOOP_CONF_DIR: "{{ hadoop_conf_dir }}"
  roles:
    - hadoop
