---
- hosts: spark
  remote_user: root
  vars_files:
   - ../vars/spark_vars.yml
   - ../vars/minio_vars.yml

  tasks:
    - include: ../roles/jupyterhub/tasks/stop-jupyterhub.yml
    - include: ../roles/spark/tasks/stop-spark.yml
