---
- name: cluster-analysis repo
  git:
    repo: https://github.com/nlesc-sherlock/cluster-analysis.git
    dest: '{{ cluster_analysis_home }}'
    update: yes
    force: yes
  run_once: true
- name: Emma owns text cluster_analysis_home
  file:
    name: '{{ cluster_analysis_home }}'
    state: directory
    owner: emma
    group: users
    recurse: yes
  run_once: true
- name: cluster-analysis pip
  pip:
    requirements: clustit/requirements.txt
    chdir: '{{ cluster_analysis_home }}'
- name: cluster-analysis Notebooks in emmas homedir
  file:
    src: '{{ cluster_analysis_home }}/clustit'
    dest: /data/local/home/emma/clustit
    state: link
  when: "'docker-swarm-manager' in group_names"
