---
- name: wheel
  pip: name=wheel
- name: libffi
  apt: name=libffi-dev
- name: libssl-dev
  apt: name=libssl-dev
- name: libyaml-dev
  apt: name=libyaml-dev
- name: htop
  apt: name=htop
- name: corporadb repo
  git:
    repo: https://github.com/nlesc-sherlock/corporadb.git
    dest: '{{ corporadb_home }}'
    update: yes
  run_once: true
- name: corporadb pip
  pip:
    requirements: requirements.txt
    chdir: '{{ corporadb_home }}'
- name: NLTK stopwords
  command: python -m nltk.downloader stopwords
  args:
    chdir: '{{ corporadb_home }}'
    creates: /usr/local/share/nltk_data/stopwords.zip
