---
- name: Text cleaning repo
  git:
    repo: https://github.com/nlesc-sherlock/text-cleaning-demo.git
    dest: '{{ text_cleaning_home }}'
    update: yes
  run_once: true
- name: text cleaning pip
  pip: name={{ item }}
  with_items:
  - scikit-learn
  - pandas
  - scriptcwl
- name: nlppln
  pip: name=git+https://github.com/WhatWorksWhenForWhom/nlppln.git#egg=nlppln editable=False
  ignore_errors: true
- name: Text cleaning notebooks in emmas homedir
  file:
    src: '{{ text_cleaning_home }}/notebooks'
    dest: /data/local/home/emma/text-cleaning-notebooks
    state: link
  when: "'docker-swarm-manager' in group_names"
